---
title: "classification_experiement_v9 - implement DIMVf"
output:
  pdf_document: default
  html_document: default
date: "2022-09-30"

fig_width: 6 
fig_height: 1.2  
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE, echo=TRUE, eval = TRUE)
``` 


```{r}
require(knitr)
FILE_NAME = 'v13'
# purl("calc_rmse_plotting.Rmd", output = 'calc_rmse_plotting.R')
```

```{r}
packages <- c(
  "missMDA", 
  "softImpute", 
  "caret", 
  "caTools", 
  "glue", 
  "jsonlite", 
  "future.apply", 
  "dslabs", 
  "cowplot", 
  "magick", 
  "progress", 
  "crunch"
)
# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE)) 

library(here) 
# source(here('src/rscript/dimv.R'))  
# source(here('src/rscript/dpers.R'))   
# source(here('src/rscript/utils.R'))    
# source(here('src/rscript/imputation_comparation.R'))     

plan(multisession, workers = 8)  

```

```{r}
#getting the path to save 

# curr_dir = getwd()
# curr_dir
path = '../../../data/fashion_mnist/raw'
curr_dir = getwd() 

mnist_path = file.path(curr_dir, path) 
print(mnist_path)

# if (!file.exists(file.path(mnist_path, "train-images-idx3-ubyte")) |
#   !file.exists(file.path(mnist_path, "t10k-images-idx3-ubyte")) |
#   !file.exists(file.path(mnist_path, "train-labels-idx1-ubyte")) |
#   !file.exists(file.path(mnist_path, "t10k-labels-idx1-ubyte")) 
#   ){
#   
#   # getting the data 
#   mnist <- read_mnist(
#     path = NULL,
#     destdir = mnist_path, 
#     download = TRUE,
#     url = "https://www2.harvardx.harvard.edu/courses/IDS_08_v2_03/",
#     keep.files = TRUE
#   )  
  
  # clear folder data (avoid wrong zipping)
  list_files = list.files(path=mnist_path) 
  print(list_files)
  for (x in 1:length(list_files)){
    file_path = file.path(mnist_path, list_files[x]) 
    if (substring(file_path, nchar(file_path)-2, nchar(file_path)) == '.gz'){
      R.utils::gunzip(file_path, overwrite=TRUE, remove=FALSE) 
    }
    }  

  
```


```{r}
# load image files
load_image_file = function(filename) {
  ret = list()
  f = file(filename, 'rb')
  readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  n    = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  nrow = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  ncol = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  x = readBin(f, 'integer', n = n * nrow * ncol, size = 1, signed = FALSE)
  close(f)
  data.frame(matrix(x, ncol = nrow * ncol, byrow = TRUE))
}

# load label files
load_label_file = function(filename) {
  f = file(filename, 'rb')
  readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  n = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  y = readBin(f, 'integer', n = n, size = 1, signed = FALSE)
  close(f)
  y
} 

```

```{r, fig.width = 6, fig.height=1.2}
# load images
processing_mnist_data <- function (){
  train = load_image_file(file.path(mnist_path, "train-images-idx3-ubyte"))
  test  = load_image_file(file.path(mnist_path,"t10k-images-idx3-ubyte")) 

  train$label =  as.factor(load_label_file(file.path(mnist_path,"train-labels-idx1-ubyte")))

  test$label = as.factor(load_label_file(file.path(mnist_path,"t10k-labels-idx1-ubyte")))
  result = list('train'=train, 'test'=test)
  return(result)
}
```  

```{r}

```


```{r, fig.width = 6, fig.height=1.2} 
# visualize the deleted images 
# visualize_digit <- function(missing_X, y, train_removed_rows, per_col=1, per_row=8){
# 
#   par(mfcol=c(per_col, per_row))
#   par(mar=c(0, 0, 3, 0), xaxs='i', yaxs='i')  
#  
#   for (idx in 1:(per_col*per_row)) { 
#       im <- matrix(unlist(missing_X[train_removed_rows, ][idx, ]),nrow = 28 ,byrow = T)
#       im <- t(apply(im, 2, rev)) 
#       image(1:28, 1:28, im,  xaxt='n', main=paste(y[train_removed_rows,,drop=F][idx, ])) 
#       
#       #image(1:28, 1:28, im, col=gray((0:255)/255), xaxt='n', main=paste(y[train_removed_rows,,drop=F][idx, ]))
#   }
# 
# }
```

```{r, fig.width = 18, fig.height=3.6}
visualize_digit_no_label <- function(missing_X, y, train_removed_rows, per_col=1, per_row=8){

  par(mfcol=c(per_col, per_row))
  par(mar=c(0, 0, 0, 0), xaxs='i', yaxs='i')  
      
  for (idx in 1:(per_col*per_row)) { 
      im <- matrix(unlist(missing_X[train_removed_rows, ][idx, ]),nrow = 28 ,byrow = T)
      im <- t(apply(im, 2, rev)) 
      image(1:28, 1:28, im,  yaxt='n', ylab = '', main=paste(y[train_removed_rows,,drop=F][idx, ]),axes = TRUE) 
      
      #image(1:28, 1:28, im, col=gray((0:255)/255), xaxt='n', main=paste(y[train_removed_rows,,drop=F][idx, ]))
  }

}
```

```{r, fig.width = 18, fig.height=4}
visualize_digit_no_label_ori <- function(missing_X, y, train_removed_rows, per_col=1, per_row=8){

  par(mfcol=c(per_col, per_row))
  par(mar=c(0,0, 7, 0), xaxs='i', yaxs='i')  
      
  for (idx in 1:(per_col*per_row)) { 
      im <- matrix(unlist(missing_X[train_removed_rows, ][idx, ]),nrow = 28 ,byrow = T)
      im <- t(apply(im, 2, rev)) 
      image(1:28, 1:28, im,  yaxt='n', ylab = '', main=paste(y[train_removed_rows,,drop=F][idx, ]),axes = TRUE, cex.main = 5) 
      
      #image(1:28, 1:28, im, col=gray((0:255)/255), xaxt='n', main=paste(y[train_removed_rows,,drop=F][idx, ]))
  }

}

```

```{r, fig.width = 18, fig.height=3.6}
processed_data = processing_mnist_data()
train = processed_data$train 
test = processed_data$test

ori.X.train = train[, -785]
ori.X.test = test[, -785]
ori.y.train = train[, 785, drop=F]
ori.y.test = test[, 785, drop=F]
 
```


```{r}
# path = "/Users/maianh/Desktop/DIMV/dimv/experiments/monotone_missing_data_imputation/fashion_mnist/../../../data/fashion_mnist/imputed/v1/threshold_10_deletedWidthHeightPc_5050_noImagePc_50/test_Gain.csv.gz" 
# 
# 
# d = read.table(path, sep=",", header=T)

```



#PLOTTING ONLY 
```{r, fig.width = 18, fig.height=3.6}
# PLOTTING ONLY 
width_height_percentages = c(.4, .5,.6)
sample_deleted_percentages = c(.5)
correlation_threshold =c(.1)
ROOT = '../../../data/fashion_mnist/imputed' 
FILE_NAME = 'v1'

for (width_height_pc in width_height_percentages){
  for (sample_deleted_percent in sample_deleted_percentages){
    for (threshold in correlation_threshold){
          width_del_percent = width_height_pc 
          height_del_percent = width_height_pc 
          width_del = toString(as.integer(width_del_percent*100))
          heigh_del =  toString(as.integer(height_del_percent*100)) 
          percent_img_del =  toString(as.integer(sample_deleted_percent*100)) 
          threshold =  as.integer(correlation_threshold*100)  
          
          threshold_string = if (as.integer(threshold/10) < 1){
            paste0("0", toString(threshold))
          }else{
            toString(threshold)
          } 
          y_test = ori.y.test[,,drop=F]
        
          sub_folder = paste0(
              "threshold_", 
              threshold_string, 
              "_deletedWidthHeightPc_", 
              width_del, 
              heigh_del, 
              '_noImagePc_', 
              percent_img_del
            ) 
          print(sub_folder)
          curr_dir = getwd() 
          sub_path = file.path(curr_dir, ROOT, FILE_NAME, sub_folder)
          print(sub_path)
          
          path.X_train_normed = file.path(sub_path, 'X_train_normed.csv.gz')
          path.X_test_normed  = file.path(sub_path, 'X_test_normed.csv.gz') 
          
        
          X_train_normed = read.table(path.X_train_normed, sep=' ', header=TRUE)  
          X_test_normed  = read.table(path.X_test_normed, sep=' ', header=TRUE)  
          
          print(dim(X_train_normed))
          print(dim(X_test_normed))
          
          test_removed_rows = as.vector(read.csv(file.path(sub_path, 'test_removed_rows.csv')))$test_removed_rows
          print(test_removed_rows[1:100])
          get_normalization_parameters <- function(Xtrain){
              mean = apply(Xtrain, 2, mean, na.rm=TRUE)
              sd = apply(Xtrain, 2, sd, na.rm=TRUE) 
              result = list("mean" = mean, "sd" = sd)
          } 

          train_missing = ori.X.train
          train_missing_pos_filter = is.na(X_train_normed)
          train_missing[train_missing_pos_filter] <- NA

          test_missing = ori.X.test
          test_missing_pos_filter = is.na(X_test_normed)
          test_missing[test_missing_pos_filter] <- NA

          params     = get_normalization_parameters(train_missing)
          train_mean = params$mean
          train_sd   = params$sd
          
          algo_list = c("knn") #c('impDi', 'softImpute', 'Gain', "knn")
          
          
          plot_path = file.path(paste0("../../../data/mnist/plot/no_label_fashion_mnist/", sub_folder)) 
          if (dir.exists("../../../data/mnist/plot/no_label_fashion_mnist/")==F){
            dir.create("../../../data/mnist/plot/no_label_fashion_mnist/")
          }  
          if (dir.exists(plot_path)==F){
            dir.create(plot_path)
          }  
          
          c = 0
          for (algo in algo_list){
                print(algo)
                path.train_imputed = file.path(sub_path, paste0('train_', algo, '.csv.gz'))
                path.test_imputed  = file.path(sub_path, paste0('test_', algo, '.csv.gz')) 
                if (algo == 'Gain'){sep = ','}else{sep= ' '} 
                print(path.train_imputed)
                print(path.test_imputed)
                
                train_imputed     = read.table(path.train_imputed, sep=sep, header=TRUE)  
                test_imputed      = read.table(path.test_imputed, sep=sep, header=TRUE)  
                print(dim(train_imputed))
                print(dim(test_imputed))
                
                train_rescaled    = reconstructingNormedMatrix(train_imputed, train_mean, train_sd)
                test_rescaled     = reconstructingNormedMatrix(test_imputed, train_mean, train_sd)
                print(dim(train_rescaled))
                print(dim(test_rescaled))
                
                rmse_train       = rmse_calc(ori.X.train, train_rescaled, train_missing_pos_filter*1)
                rmse_test        = rmse_calc(ori.X.test, test_rescaled, test_missing_pos_filter*1)

                result = data.frame(list("name" = sub_folder, "method" = algo, "rmse_train" = rmse_train, "rmse_test" = rmse_test))

                print(paste0("algo ", algo, 'rmse_train ', rmse_train, " rmse_tesst ", rmse_test))

                if (c ==0 ){
                  results = result
                }else{
                  results = rbind(results, result)
                }
                c = c + 1

                if (algo == "impDi"){
                   Xtest_impDi_rescaled = test_rescaled
                }else if(algo == "softImpute") {
                  Xtest_softImpute_rescaled = test_rescaled
                }else if(algo == "Gain"){
                  Xtest_Gain_rescaled = test_rescaled
                }else{
                  Xtest_knn_rescaled = test_rescaled
                }
          }
          
          # SAVE RESULT
          write.csv(results, file.path(sub_path, 'rmse_knn.csv'))

          # softImputeImgPath <- file.path(plot_path, "softImpute_test.png")
          # png(softImputeImgPath, width=dev.size("px")[1] , height = dev.size("px")[2])
          # visualize_digit_no_label(Xtest_softImpute_rescaled, y_test, test_removed_rows, 1, 8)
          # dev.off()
          # 
          # GainImgPath <- file.path(plot_path, "Gain_test.png")
          # png(GainImgPath, width = dev.size("px")[1], height = dev.size("px")[2])
          # visualize_digit_no_label(Xtest_Gain_rescaled, y_test, test_removed_rows, 1, 8)
          # dev.off()
          
          knnImgPath <- file.path(plot_path, "knn_test.png")
          png(knnImgPath, width = dev.size("px")[1], height = dev.size("px")[2])
          visualize_digit_no_label(Xtest_knn_rescaled, y_test, test_removed_rows, 1, 8)
          dev.off()
          # 
          # impDiImgPath <- file.path(plot_path, "impDi_test.png")
          # png(impDiImgPath, width = dev.size("px")[1], height = dev.size("px")[2])
          # visualize_digit_no_label(Xtest_impDi_rescaled, y_test, test_removed_rows, 1, 8)
          # dev.off()
          # 
          # OriImgPath <- file.path(plot_path, "ori_test.png")
          # png(OriImgPath, width = dev.size("px")[1], height = dev.size("px")[2])
          # visualize_digit(ori.X.test, y_test, test_removed_rows, 1, 8)
          # dev.off()
          # 
          # OriMissingImgPath <- file.path(plot_path, "ori_missing_test.png")
          # png(OriMissingImgPath, width = dev.size("px")[1], height = dev.size("px")[2])
          # visualize_digit_no_label(test_missing, y_test, test_removed_rows, 1, 8)
          # dev.off()
          # 
          # merged_width = 300 #dev.size("px")[1]
          # merged_height = 300*5+50 #dev.size("px")[2]*2+50
          # 
          # p1 <- ggdraw() + draw_image(OriImgPath)
          # p2 <- ggdraw() + draw_image(OriMissingImgPath)
          # p3 <- ggdraw() + draw_image(softImputeImgPath)
          # p4 <- ggdraw() + draw_image(GainImgPath)
          # p5 <- ggdraw() + draw_image(impDiImgPath)
          # 
          # imgPath =  file.path(plot_path, "img.png")
          # 
          # png(imgPath) #,  width = merged_width, height = merged_height)
          # 
          # plot_grid(p1, p2, p3, p4, p5,
          #           nrow = 5,
          #           ncol=1,
          #           labels =  NULL,
          #           label_size = 12,
          #           scale=1,
          #           vjust=c(2.0, 2.0, 2.0, 2.0),
          #           label_colour = "blue")
          # 
          # dev.off()
          # #
          print(paste0("Complete saving plot, pipeline is done ", sub_folder))
    }

  }

}
``` 



```{r, fig.width = 18, fig.height=3.6}
          softImputeImgPath <- file.path(plot_path, "softImpute_test.png")
          png(softImputeImgPath, width=dev.size("px")[1] , height = dev.size("px")[2])
          visualize_digit_no_label(Xtest_softImpute_rescaled, y_test, test_removed_rows, 1, 8)
          dev.off()
        
          GainImgPath <- file.path(plot_path, "Gain_test.png")
          png(GainImgPath, width = dev.size("px")[1], height = dev.size("px")[2])
          visualize_digit_no_label(Xtest_Gain_rescaled, y_test, test_removed_rows, 1, 8)
          dev.off()
        
          impDiImgPath <- file.path(plot_path, "impDi_test.png")
          png(impDiImgPath, width = dev.size("px")[1], height = dev.size("px")[2])
          visualize_digit_no_label(Xtest_impDi_rescaled, y_test, test_removed_rows, 1, 8)
          dev.off()
          

          
          OriMissingImgPath <- file.path(plot_path, "ori_missing_test.png")  
          png(OriMissingImgPath, width = dev.size("px")[1], height = dev.size("px")[2]) 
          visualize_digit_no_label(test_missing, y_test, test_removed_rows, 1, 8) 
          dev.off() 
          
          merged_width = 300 #dev.size("px")[1]
          merged_height = 300*5+50 #dev.size("px")[2]*2+50
        
          p1 <- ggdraw() + draw_image(OriImgPath)
          p2 <- ggdraw() + draw_image(OriMissingImgPath)
          p3 <- ggdraw() + draw_image(softImputeImgPath)
          p4 <- ggdraw() + draw_image(GainImgPath)
          p5 <- ggdraw() + draw_image(impDiImgPath)
        
          imgPath =  file.path(plot_path, "img.png")
        
          png(imgPath) #,  width = merged_width, height = merged_height)
        
          plot_grid(p1, p2, p3, p4, p5,
                    nrow = 5,
                    ncol=1,
                    labels =  NULL,
                    label_size = 12,
                    scale=1,
                    vjust=c(2.0, 2.0, 2.0, 2.0),
                    label_colour = "blue")
        
          dev.off()
          #
          print(paste0("Complete saving plot, pipeline is done ", sub_folder))
          
```



```{r, fig.width = 6, fig.height=1.2}
# width_height_percentages =c(.6, .5, .4)
# sample_deleted_percentages = c(.5)
# correlation_threshold =c(.1)
# ROOT = '../../../data/mnist/imputed' 
# 
# for (width_height_pc in width_height_percentages){
#   for (sample_deleted_percent in sample_deleted_percentages){
#     for (threshold in correlation_threshold){
#           width_del_percent = width_height_pc 
#           height_del_percent = width_height_pc 
#           width_del = toString(as.integer(width_del_percent*100))
#           heigh_del =  toString(as.integer(height_del_percent*100)) 
#           percent_img_del =  toString(as.integer(sample_deleted_percent*100)) 
#           threshold =  as.integer(correlation_threshold*100)  
#           
#           threshold_string = if (as.integer(threshold/10) < 1){
#             paste0("0", toString(threshold))
#           }else{
#             toString(threshold)
#           } 
#           y_test = ori.y.test[,,drop=F]
#         
#           sub_folder = paste0(
#               "threshold_", 
#               threshold_string, 
#               "_deletedWidthHeightPc_", 
#               width_del, 
#               heigh_del, 
#               '_noImagePc_', 
#               percent_img_del
#             ) 
#           curr_dir = getwd() 
#           sub_path = file.path(curr_dir, ROOT, FILE_NAME, sub_folder)
#           print(sub_path)
#           
#           path.X_train_normed = file.path(sub_path, 'X_train_normed.csv.gz')
#           path.X_test_normed  = file.path(sub_path, 'X_test_normed.csv.gz') 
#           
#         
#           X_train_normed = read.table(path.X_train_normed, sep=' ', header=TRUE)  
#           X_test_normed  = read.table(path.X_test_normed, sep=' ', header=TRUE)  
#           
#           print(dim(X_train_normed))
#           print(dim(X_test_normed))
#           
#           test_removed_rows = as.vector(read.csv(file.path(sub_path, 'test_removed_rows.csv')))$test_removed_rows
# 
#           get_normalization_parameters <- function(Xtrain){
#               mean = apply(Xtrain, 2, mean, na.rm=TRUE)
#               sd = apply(Xtrain, 2, sd, na.rm=TRUE) 
#               result = list("mean" = mean, "sd" = sd)
#           } 
#           
#           train_missing = ori.X.train
#           train_missing_pos_filter = is.na(X_train_normed) 
#           train_missing[train_missing_pos_filter] <- NA  
#           
#           test_missing = ori.X.test
#           test_missing_pos_filter = is.na(X_test_normed)
#           test_missing[test_missing_pos_filter] <- NA  
#           
#           params     = get_normalization_parameters(train_missing)
#           train_mean = params$mean
#           train_sd   = params$sd 
#           
#           algo_list = c('impDi', 'softImpute', 'Gain')
#           
#           
#           plot_path = file.path(paste0("../../../data/mnist/plot/nolabel/", sub_folder)) 
#           if (dir.exists("../../../data/mnist/plot/nolabel/")==F){
#             dir.create("../../../data/mnist/plot/nolabel/")
#           }  
#           if (dir.exists(plot_path)==F){
#             dir.create(plot_path)
#           }  
#           
#           c = 0
#           for (algo in algo_list){
#                 print(algo)
#                 path.train_imputed = file.path(sub_path, paste0('train_', algo, '.csv.gz'))
#                 path.test_imputed  = file.path(sub_path, paste0('test_', algo, '.csv.gz')) 
#                 if (algo == 'Gain'){sep = ','}else{sep= ' '} 
#                 print(path.train_imputed)
#                 print(path.test_imputed)
#                 
#                 train_imputed     = read.table(path.train_imputed, sep=' ', header=TRUE)  
#                 test_imputed      = read.table(path.test_imputed, sep=' ', header=TRUE)  
#                 print(dim(train_imputed))
#                 print(dim(test_imputed))
#                 
#                 train_rescaled    = reconstructingNormedMatrix(train_imputed, train_mean, train_sd)
#                 test_rescaled     = reconstructingNormedMatrix(test_imputed, train_mean, train_sd)
#                 print(dim(train_rescaled))
#                 print(dim(test_rescaled))
#                 
#                 rmse_train       = rmse_calc(ori.X.train, train_rescaled, train_missing_pos_filter*1)
#                 rmse_test        = rmse_calc(ori.X.test, test_rescaled, test_missing_pos_filter*1)
#                 
#                 result = data.frame(list("name" = sub_folder, "method" = algo, "rmse_train" = rmse_train, "rmse_test" = rmse_test))
#                 
#                 print(paste0("algo ", algo, 'rmse_train ', rmse_train, " rmse_tesst ", rmse_test))
#                 
#                 if (c ==0 ){
#                   results = result
#                 }else{
#                   results = rbind(results, result)
#                 }
#                 c = c + 1
#         
#                 if (algo == "impDi"){
#                   Xtest_impDi_rescaled = test_rescaled 
#                 }else if(algo == "softImpute") {
#                   Xtest_softImpute_rescaled = test_rescaled 
#                 }else{
#                   Xtest_Gain_rescaled = test_rescaled
#                 }
#           }
#           
#           # SAVE RESULT
#           write.csv(results, file.path(sub_path, 'rmse.csv')) 
#         
#           softImputeImgPath <- file.path(plot_path, "softImpute_test.png")
#           png(softImputeImgPath, width=dev.size("px")[1] , height = dev.size("px")[2])
#           visualize_digit_no_label(Xtest_softImpute_rescaled, y_test, test_removed_rows, 1, 8)
#           dev.off()
#         
#           GainImgPath <- file.path(plot_path, "Gain_test.png")
#           png(GainImgPath, width = dev.size("px")[1], height = dev.size("px")[2])
#           visualize_digit_no_label(Xtest_Gain_rescaled, y_test, test_removed_rows, 1, 8)
#           dev.off()
#         
#           impDiImgPath <- file.path(plot_path, "impDi_test.png")
#           png(impDiImgPath, width = dev.size("px")[1], height = dev.size("px")[2])
#           visualize_digit_no_label(Xtest_impDi_rescaled, y_test, test_removed_rows, 1, 8)
#           dev.off()
#           
#           OriImgPath <- file.path(plot_path, "ori_test.png")  
#           png(OriImgPath, width = dev.size("px")[1], height = dev.size("px")[2]) 
#           visualize_digit(ori.X.test, y_test, test_removed_rows, 1, 8) 
#           dev.off()
#           
#           OriMissingImgPath <- file.path(plot_path, "ori_missing_test.png")  
#           png(OriMissingImgPath, width = dev.size("px")[1], height = dev.size("px")[2]) 
#           visualize_digit_no_label(test_missing, y_test, test_removed_rows, 1, 8) 
#           dev.off() 
#           
#           merged_width = 300 #dev.size("px")[1]
#           merged_height = 300*5+50 #dev.size("px")[2]*2+50
#         
#           p1 <- ggdraw() + draw_image(OriImgPath)
#           p2 <- ggdraw() + draw_image(OriMissingImgPath)
#           p3 <- ggdraw() + draw_image(softImputeImgPath)
#           p4 <- ggdraw() + draw_image(GainImgPath)
#           p5 <- ggdraw() + draw_image(impDiImgPath)
#         
#           imgPath =  file.path(plot_path, "img.png")
#         
#           png(imgPath) #,  width = merged_width, height = merged_height)
#         
#           plot_grid(p1, p2, p3, p4, p5,
#                     nrow = 5,
#                     ncol=1,
#                     labels =  NULL,
#                     label_size = 12,
#                     scale=1,
#                     vjust=c(2.0, 2.0, 2.0, 2.0),
#                     label_colour = "blue")
#         
#           dev.off()
#           #
#           print(paste0("Complete saving plot, pipeline is done ", sub_folder))
#     }
# 
#   }
# 
# }
# 
#  
```
